### ISSUE TITLE
Step must be a `string`

### ISSUE THREAD

**Issue by lougreenwood** [alexlafroscia/ember-steps#100]
HI,

I'm trying to dynamically generate step names (so I can send a button to each step to another part of the page using `ember-elsewhere`).

To achieve this, I'm attempting to define a step name using the output of a helper:

`{{#w.step name=(html-safe (dasherize module.name))}}`
(using ember-cli-string-helpers from here: https://github.com/romulomachado/ember-cli-string-helpers)

where `module.name` is a name of the step.

However, I get this error in console:
`Step must be a `string``

but it seems to me that the output of that helper is a string - so I'm guessing that the type-checking is too strict?

I'm using V 4.0

**Comment by alexlafroscia** [comment]
Is there a reason you're wrapping in `html-safe`? If memory serves me correctly, that returns an `SafeString` which is actually an object that wraps a string.

Just doing

```handlebars
{{#w.step name=(dasherize module.name)}}
{{/w.step}}
```

should work.

**Comment by lougreenwood** [comment]
Yes, you're completely right - thanks

**Comment by alexlafroscia** [comment]
No problem! Happy to help.

**Comment by alexlafroscia** [comment]
Out of curiosity, what does using it with `ember-elsewhere` look like? Might be worth adding an example to the cookbook; I'm trying to document examples of lots of different patterns one might want to achieve with `ember-steps`.
