### ISSUE TITLE
Not possible to use 0 number for step name

### ISSUE THREAD

**Issue by lougreenwood** [alexlafroscia/ember-steps#112]
I'm currently building a pagination component using Ember Steps.

I'm naming each step in my component using the index of an array where each array item contains the objects to display on each page.

However, it seems that using name=0 doesn't work, the issues are:

* When `currentStep=0`, then ember steps ignores this and uses the next step in the sequence
* When on `currentStep=1`, emitting the action `w.transition-to-previous`, a console error of `Error: Assertion Failed: There is no previous step` is logged

However, curiously `w.transition-to 0` works fine... 😎 

Here's a repro: https://ember-twiddle.com/d104a7154fe3af204e1d6a758b5bcf87?openFiles=templates.application.hbs%2C

Steps to reproduce:

* On twiddle load, notice that `currentStep=0` but you see the message `I am Step #2 with index #1`
  * Instead you should see the message `I am Step #1 with index #0`
* On twiddle load, press 'Back' button, see `Error: Assertion Failed: There is no previous step` in console
  * Instead, this should transition to previous step which has `name=0`
* On twiddle load, click '1' button, see ember steps transition to step name=0
  * This is working as expected, but helps to demonstrate that some areas of Ember Steps can indeed accept 0 as a step name

**Comment by alexlafroscia** [comment]
Hey, thanks for catching this and reporting! I'll get this fixed up.

**Comment by alexlafroscia** [comment]
Also: thank you SO much for the reproduction. I know that takes a bit of effort on your end, but it's incredible helpful to diagnose something like this!

**Comment by lougreenwood** [comment]
No problem, it’s not an easy bug to explain - also, it’s only polite considering the work you put into the add on!

**Comment by alexlafroscia** [comment]
^ Once CI passes on that PR, I'll merge and a release should be cut automatically (assuming `semantic-release` is working again -- it broke for a bit but should be OK now).

The problem ended up being something pretty dumb on my part -- I was checking essentially checking `!initialStepName` when starting the state machine to see if it was given a specific step when starting, when what I really wanted was to check if the value was present. `0` was throwing it off because it's falsy, but present. Simply moving to a more robust means for checking the initial step name fixed the bug, and I added a handful of tests to avoid a regression in the future.

Thanks again for the bug report!

**Comment by lougreenwood** [comment]
Thanks - I figured it would probably be something simple like that 😃 

BTW - looks like the automated release is failing: https://github.com/alexlafroscia/ember-steps/issues/110

**Comment by lougreenwood** [comment]
I've just had a chance to test 6.0.1 - looks like it only half fixed the issue :(

I've updated the twiddle to use 6.0.1, the remaining issue is...

* navigate to page 2
* press the 'back' pagination button
* see that steps doesn't go back
* see `Error: Assertion Failed: There is no previous step` console error

**Comment by lougreenwood** [comment]
Ok, this is weird, seems it's now working locally for me (no idea what changed 😄), and I see that you added tests for previous step being falsy, but the ember twiddle continues to error when attempting to go to previous from step 1 to 0... odd 😕

**Comment by alexlafroscia** [comment]
The Twiddle was updated to the latest version of the code (`6.0.1`)? I don't know if it would update on its own, you might have to manually bump the version

**Comment by alexlafroscia** [comment]
Yeah, I found the problem. There are other `!!` checks that should explicitly compare against `undefined`. I'll get that fixed and another release cut!

**Comment by lougreenwood** [comment]
coolio - thanks for addressing this so quickly!! 🏅

**Comment by alexlafroscia** [comment]
No problem! The auto-release gears should be turning and a comment will be posted here when `6.0.2` is out!
