### ISSUE TITLE
action hooks for step becoming active/inactive

### ISSUE THREAD

**Issue by lougreenwood** [alexlafroscia/ember-steps#116]
Is there any mechanism to pass an action to be executed when a step becomes active or inactive?

**Comment by alexlafroscia** [comment]
Not yet, but that's something I'd be willing to support!

Are you looking for a single action that would fire for _any_ step being activated or deactivated? Or defining an action for each specific step?

**Comment by lougreenwood** [comment]
An action per-step - let me know if there’s anything I can do to help - doesn’t seem like it would be a big task, I imagine something like:

Allow passing 2 new properties to a step:

- onShow
- onHide

Call these passed actions in some (new) hooks (something like didRender() & didDestroy() - but Ember-step lifecycle specific)?

**Comment by alexlafroscia** [comment]
Makes sense to me! I have someone in mind to give tackling this feature a chance -- we'll work on that this weekend and see if we can get this feature added.

**Comment by lougreenwood** [comment]
@alexlafroscia looks like the 6.1.0 release failed/isn't available on NPM

**Comment by alexlafroscia** [comment]
Yeah, I'll be fixing that today. Part of my auto-deploy script works and part doesn't -- the GitHub tag works but the NPM publish is broken!

I'll ping this thread once `6.1.0` is deployed.

**Comment by lougreenwood** [comment]
np, let me know if I can help :)

**Comment by alexlafroscia** [comment]
This was just released as `6.1.1` (`6.1.0` had a TypeScript compilation error so I'm not even going to bother releasing it to `npm`).
