### ISSUE TITLE
Dynamic Definition of Steps (Cookbook) behaving strangely

### ISSUE THREAD

**Issue by pepke41** [alexlafroscia/ember-steps#117]
There are three steps defined in the component.js, but a fourth empty state is being shown in the example code. http://alexlafroscia.com/ember-steps/latest/docs/cookbook/dynamic-definition

**Comment by artikhurana** [comment]
Any updates for this. I'm facing the same issue. Please suggest

**Comment by artikhurana** [comment]
Earlier I was using ember-steps 2.1.6 not able to create a dynamic name in steps. After that I tried with ember-steps 6.0.0 version was able to create a dynamic name.
So you can close this issue.
Thanks
