### ISSUE TITLE
Stage 2 decorators support

### ISSUE THREAD

**Issue by knownasilya** [alexlafroscia/ember-steps#131]
I'm getting the following error with stage 2 decorators.

> WARNING: The 'ember-steps' addon is using an older version of ember-cli-typescript that uses stage 1 decorators. Please update to ember-cli-typescript@v2 to remove your dependency on legacy decorators.

In my app I'm using `"ember-cli-typescript": "2.0.0-rc.1"`

**Comment by alexlafroscia** [comment]
Sorry about this — I’ll try to get this updated very soon and would totally welcome a PR to upgrade if you have the time!

**Comment by alexlafroscia** [comment]
I think I worked out what's happening, it was the `ember-cli-babel` and/or `ember-cli-typescript` version being a little out-of-date with regard to decorators support. Working on a fix now 👍

**Comment by alexlafroscia** [comment]
Currently getting stuck on this:

https://github.com/typed-ember/ember-cli-typescript/issues/496

**Comment by alexlafroscia** [comment]
You should be able to upgrade to `v7.0.0` and resolve this issue 👍
