### ISSUE TITLE
validate-transition with transition-to 'named'

### ISSUE THREAD

**Issue by kwatson** [alexlafroscia/ember-steps#143]
Hi,

I'm not able to get `validate-transition` to work when transitioning to a named step. Is that not supported?

**This works:** 

`validate-transition w.transition-to-next with=(action "performValidation")`

_and_

`action w.transition-to 'myStep'`

**But not this:**
`validate-transition w.transition-to 'myStep' with=(action "performValidation")`

Thanks for any help..

**Comment by alexlafroscia** [comment]
Hey! Sorry you're running into an issue here.

`validation-transition` takes an action (or function) as a second parameter. Do in this case, you'll want to provide an action that is partially applied (pre-filled) with the `myStep` argument:

```
validate-transition (action w.transition-to 'myStep') with=(action "performValidation")
```

That should work for you, but if it does not, please let me know and I'll see what I can do to help!
