### ISSUE TITLE
Cannot read property 'addStep' of undefined

### ISSUE THREAD

**Issue by aonawale** [alexlafroscia/ember-steps#149]
Ember 3.10

```
{{#step-manager as |w|}}
  {{#w.step name='a'}}
    This is the first step!
  {{/w.step}}

  {{#w.step name='b'}}
    This is the second step!
  {{/w.step}}
{{/step-manager}}
```

Looks like this was reported but closed without being investigated. https://github.com/alexlafroscia/ember-steps/issues/138

**Comment by alexlafroscia** [comment]
I see you closed this @aonawale -- did the issue go away? How did you fix it ?
