### ISSUE TITLE
RFC: SEO friendly steps?

### ISSUE THREAD

**Issue by lougreenwood** [alexlafroscia/ember-steps#150]
I've recently been focusing on improving the SEO scores of one of my sites.

This site currently uses a step manager on the home page for a kind of "feature explorer" where features are listed as steps and a user can click on a button and learn more about the feature.

By default, this displays the first feature, but because ember-steps dynamically generates the DOM for the current step's element, the other steps are missing from the DOM.

For example:
```
{{#step-manager as |w|}}
  {{#w.step name='a'}}
    This is the first step!
  {{/w.step}}

  {{#w.step name='b'}}
    This is the second step!
  {{/w.step}}
{{/step-manager}}
```

Would only create `This is the first step!` in the DOM - `This is the second step!` would be missing from the DOM. In terms of SEO, this means that any content in other steps cannot contribute to the page's SEO score.

This got me thinking about how to solve this, and whether ember-steps is the right solution for my problem.

**So my question is:**

Would it be both in scope and a good idea for `ember-steps` to have 2 different modes of operation.
* The current behaviour which conditionally creates the content for each step
* Some new "SEO-friendly" mode which instead creates all steps in the DOM and applies "display: none" (or similar) to all currently disabled steps.

**Comment by alexlafroscia** [comment]
Thanks for opening the issue @lougreenwood! I'm glad this is something that you're thinking about.

> Would it be both in scope and a good idea for ember-steps to have 2 different modes of operation.

I'm going to go ahead and say "no". There would be too much nuance in the differences between how the current behavior and the proposed "SEO friendly" behavior would work.

Consider some `foo-bar` component with a `didInsertElement` and `willDestroyElement` hook that is rendered inside a step.

In the current behavior, `didInsertElement` will fire only once the step is made visible, and `willDestroyElement` will fire when the step is made inactive.

If we're using CSS to change the visibility instead, `didInsertElement` would fire for every component in all steps on the first render, and `willDestroyElement` will only fire once the entire step manager is unmounted. Additionally, I don't like the idea of needing to do the work to render all of the steps and only have one actually visible.

I'm happy to continue the discussion, but I think it's just beyond the scope of what I want to support here.

**Comment by lougreenwood** [comment]
hehe no worries - I figured that it might be contentious given the scope of the addon :)

I had the same thoughts around `did-insert/will-destroy` - we'd need to add the `onActivate` back again to get parity between the 2 features - which is less than ideal. 🤣 

I wonder if I can use the step-manager's state machine to track the currently active step, but not use `<W.step>` to contain the content... at a glance that usage with some extra logic for css hiding inactive steps may be good enough to allow me to have the best of both worlds without any upstream changes.

Depending on the result of that little experiment, I'll PR an update to the README/docs with either a disclaimer about the drawbacks when using `ember-steps` for important SEO content OR I'll share an example of my above experiment if it's successful.

**Comment by alexlafroscia** [comment]
That sounds great! Let me know how that goes.

If refactoring something internally would allow you to subclass the step manager and pull off the customization you want, that's something I'd be willing to do. I just don't think it makes sense as a feature of the addon.
