### ISSUE TITLE
A component or helper named "control-group" could not be found. (ember-steps@9.0.0)

### ISSUE THREAD

**Issue by arun-prasad-r** [alexlafroscia/ember-steps#153]
Hi @alexlafroscia, 

I've installed **v9.0.0** of ember-steps. 

I'm not able to user the **{{control-group}}** component following the cookbook.
When I try to use control-group, I get the following error.

> Assertion Failed: A component or helper named "control-group" could not be found.

**Comment by alexlafroscia** [comment]
The `control-group` component isn't part of the add-on -- it's actually just something that I put together for the documentation site! The `step-manager` and yielded `.step` component is what should be used from the add-on.
