### ISSUE TITLE
Proposal: make the components tagless

### ISSUE THREAD

**Issue by zeppelin** [alexlafroscia/ember-steps#65]
Sure, a breaking change, but it would be great if the tags would diappear from the components. As their purpose is purely just to display their content, `tagName: ''` would make styling flexbox layouts a lot easier. I don't think that losing event handling (click, etc) is an issue in this case.

**Comment by alexlafroscia** [comment]
Hmm, that's interesting! I've never played around with this before, but I know it's possible (I've seen other addons do it).

If you want to spike this change and submit a PR, I'd love to take a look at it.

**Comment by zeppelin** [comment]
Sure, I'm using it already in my own fork!

**Comment by alexlafroscia** [comment]
Closed by #75

**Comment by zeppelin** [comment]
Thank you, excellent work!
