### ISSUE TITLE
Deprecation warning for `didUpdateAttrs` and `didReceiveAttrs`

### ISSUE THREAD

**Issue by YoranBrondsema** [alexlafroscia/ember-steps#70]
The arguments to the `didUpdateAttrs` and `didReceiveAttrs` will disappear in Ember.js 2.13 (see https://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks). An alternative is to use [ember-diff-attrs](https://github.com/workmanw/ember-diff-attrs), which provides the same functionality.

**Comment by alexlafroscia** [comment]
Yup, working on it. See #69

**Comment by YoranBrondsema** [comment]
Ah sorry, didn't see that PR! Yes indeed, the addon takes care of the manual value tracking that is being done in the PR.

**Comment by alexlafroscia** [comment]
I was able to implement a fix without the addon, but it's good to know about. I'm really glad I wrote all those tests when I first wrote all this, since now I can refactor without worrying about anything breaking!

**Comment by YoranBrondsema** [comment]
Hehe good tests always pay off :-). Thanks for the addon btw!

**Comment by alexlafroscia** [comment]
Sure thing, really glad that other people are finding it useful!

**Comment by alexlafroscia** [comment]
This should be closed by the `0.13.0` release.
