### ISSUE TITLE
Expose an array of step names

### ISSUE THREAD

**Issue by alexlafroscia** [alexlafroscia/ember-steps#8]
# What is it?

``` hbs
{{#step-manager as |w|}}
  <ul>
    {{#each w.steps as |stepName|}}
      <li>{{stepName}}
    {{/each}}
  </ul>

  {{w.step name='foo'}}
  {{w.step name='bar'}}
{{/step-manager}}
```

Which is useful in situations where people want to build something like progress dots as they progress through the steps.  It can still be done without this, but it would be easier if you could iterate over the step names dynamically.
# The Challenge

If the steps register themselves at render time, then `w.steps` will be updated multiple times during the render cycle.  This data will need to be provided to the `step-manager` at build time.  Technically, all of the relevant information exists at build time, but it needs to be provided somehow to the `step-manager` component.

**Comment by willrax** [comment]
This addon could possibly help here: https://github.com/miguelcobain/ember-composability-tools

**Comment by alexlafroscia** [comment]
Oh cool! Never seen that before, but it definitely looks useful! I'll have to check that out and see if it solves some of the problems I was seeing.
