### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by KamiKillertO** [alexlafroscia/ember-steps#81]
There's a small typo in this page https://github.com/alexlafroscia/ember-steps/wiki/Using-Steps-as-Data

The typo is located in the example : 
```html
 <button {[action w.transition-to-next}}>
    Next
  </button>
```

There's `{[` instead of `{{` before `action`

**Comment by YoranBrondsema** [comment]
Thanks for noticing! Feel free to fix it in a PR ;-)

**Comment by alexlafroscia** [comment]
Fixed, thanks!
