### ISSUE TITLE
calling set on destroyed object

### ISSUE THREAD

**Issue by Bartheleway** [alexlafroscia/ember-steps#82]
Hi,

I found an error in my previous PR about the async `will-transition` update. Because `will-transition` is asynchronous, the `finally` execution appends in a different run loop. It should not be a big deal in most cases but it may appends to trigger the following error : `Assertion Failed: calling set on destroyed object`.

This appends if (like me), you actually destroy the component during the call of your `will-transition` action.

**Comment by alexlafroscia** [comment]
Closed by #83
