### ISSUE TITLE
Transition to previous step

### ISSUE THREAD

**Issue by robert-j-webb** [alexlafroscia/ember-steps#84]
Hi,

Would the maintainers be interested in a PR that would expose the functionality to transition backwards? I'd write tests :)

**Comment by alexlafroscia** [comment]
This should already be supported

https://github.com/alexlafroscia/ember-steps/blob/3300d9f5aef8a73a902bebff3274a3c5a6f1661a/addon/components/step-manager.js#L16

Is that not working?

**Comment by robert-j-webb** [comment]
Ah I didn't see that! I didn't look through the source code. I could add to the documentation instead that this feature exists if you want?

**Comment by alexlafroscia** [comment]
I'm actually working on a total re-write of the documentation using [`ember-cli-addon-docs`](https://github.com/ember-learn/ember-cli-addon-docs), so I'll take care of it. Thanks, though!
