### ISSUE TITLE
Yield information about whether a step has a next/previous

### ISSUE THREAD

**Issue by alexlafroscia** [alexlafroscia/ember-steps#86]
- [x] Make the cyclical nature of the `step-manager` optional
- [x] `yield` information about the next/previous step into the `step` component block

***

This would be a breaking change; make sure to call it out in the changelog

## Example API

```hbs
{{#w.step name='foo' as |step|}}
  {{step.next}}
  {{step.previous}}
{{/w.step}}
```

- Name of the step if available
- `undefined` if not
- Allows people to dynamically show/hide UI based on the relationship to other steps

cc: @offirgolan

**Comment by offirgolan** [comment]
I would also consider adding `hasNext` and `hasPrevious` to both the step and the step manager.

**Comment by alexlafroscia** [comment]
That’s the plan :)
